micronaut:
  application:
    name: mnQuickstart
  server:
    port: 8090
netty:
  default:
    allocator:
      max-order: 3
hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hallo Welt"
      en: "Hello World"
